server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/flying-bs/cloud2021-config.git #GitHub上面的git仓库名字
         # uri: git@github.com:flying-bs/cloud2021-config.git #GitHub上面的git仓库名字
        ####搜索目录
          search-paths:
            - cloud2021-config
      ####读取分支
      label: main
      #label: master

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka